config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :cardsets do
    resources :cards, except: [:index, :show]

    get :presentation, to: "presentations#show"
  end

  resources :presentations, only: :index
  resources :categories, except: :show

  namespace :api do
    resources :cardsets, only: :show
    resources :categories, only: :index
  end

  root to: redirect("/presentations")
end

# == Route Map
#
#               Prefix Verb   URI Pattern                                    Controller#Action
#     new_user_session GET    /users/sign_in(.:format)                       devise/sessions#new
#         user_session POST   /users/sign_in(.:format)                       devise/sessions#create
# destroy_user_session DELETE /users/sign_out(.:format)                      devise/sessions#destroy
#        cardset_cards POST   /cardsets/:cardset_id/cards(.:format)          cards#create
#     new_cardset_card GET    /cardsets/:cardset_id/cards/new(.:format)      cards#new
#    edit_cardset_card GET    /cardsets/:cardset_id/cards/:id/edit(.:format) cards#edit
#         cardset_card PATCH  /cardsets/:cardset_id/cards/:id(.:format)      cards#update
#                      PUT    /cardsets/:cardset_id/cards/:id(.:format)      cards#update
#                      DELETE /cardsets/:cardset_id/cards/:id(.:format)      cards#destroy
# cardset_presentation GET    /cardsets/:cardset_id/presentation(.:format)   presentations#show
#             cardsets GET    /cardsets(.:format)                            cardsets#index
#                      POST   /cardsets(.:format)                            cardsets#create
#          new_cardset GET    /cardsets/new(.:format)                        cardsets#new
#         edit_cardset GET    /cardsets/:id/edit(.:format)                   cardsets#edit
#              cardset GET    /cardsets/:id(.:format)                        cardsets#show
#                      PATCH  /cardsets/:id(.:format)                        cardsets#update
#                      PUT    /cardsets/:id(.:format)                        cardsets#update
#                      DELETE /cardsets/:id(.:format)                        cardsets#destroy
#        presentations GET    /presentations(.:format)                       presentations#index
#           categories GET    /categories(.:format)                          categories#index
#                      POST   /categories(.:format)                          categories#create
#         new_category GET    /categories/new(.:format)                      categories#new
#        edit_category GET    /categories/:id/edit(.:format)                 categories#edit
#             category PATCH  /categories/:id(.:format)                      categories#update
#                      PUT    /categories/:id(.:format)                      categories#update
#                      DELETE /categories/:id(.:format)                      categories#destroy
#          api_cardset GET    /api/cardsets/:id(.:format)                    api/cardsets#show
#       api_categories GET    /api/categories(.:format)                      api/categories#index
#                 root GET    /                                              redirect(301, /presentations)

app/models/cardset.rb
# frozen_string_literal: true

class Cardset < ApplicationRecord
  has_many :cards,
           dependent: :destroy

  validates :title,
            presence: true
end

# == Schema Information
#
# Table name: cardsets
#
#  id         :bigint           not null, primary key
#  title      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/api/cardsets_controller.rb
# frozen_string_literal: true

module API
  class CardsetsController < ApplicationController
    def show
      @cardset = cardset
    end

    private

    def cardset
      @cardset ||= Cardset.find(params[:id])
    end
  end
end

app/controllers/cardsets_controller.rb
# frozen_string_literal: true

class CardsetsController < ApplicationController
  before_action :authenticate_user!

  def index; end

  def new
    @cardset = Cardset.new
  end

  def create
    @cardset = Cardset.new(cardset_params)

    if @cardset.save
      redirect_to cardsets_path
    else
      render "new"
    end
  end

  def edit
    @cardset = cardset
  end

  def update
    @cardset = cardset

    if @cardset.update(cardset_params)
      redirect_to cardsets_path
    else
      render "edit"
    end
  end

  def destroy
    @cardset = cardset
    @cardset.destroy

    redirect_to cardsets_path
  end

  def show
    @cardset = cardset
  end

  private

  def cardset_params
    params
      .require(:cardset)
      .permit(:title)
  end

  def cardset
    @cardset ||= Cardset.find(params[:id])
  end
end

app/views/cardsets/_form.html.erb
<% if @cardset.errors.any? %>
<div id="error_explanation" class="alert alert-danger">
  <strong><%= pluralize(@cardset.errors.count, t('error')) %> <%= t('cardset_errortext') %></strong>
  <ul>
  <% @cardset.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <%= f.text_field :title, :class => "form-control floating-label", :placeholder => t('title').capitalize, :required => "true" %>
</div>

<% if params[:action] != 'new' %>
<%= f.submit t('action_update'), :class => "btn" %>
<% else %>
<%= f.submit t('action_add'), :class => "btn" %>
<% end %>

app/views/cardsets/edit.html.erb
<div class="row row-animated">
  <div class="col-md-6 col-md-offset-3">
    <h2 class="list-title">
      <%= link_to cardsets_path, :class => "link-icon icon-xl" do %>
        <i class="mdi-navigation-arrow-back"></i>
      <% end %>
    <%= t('action_edit') %>
    </h2>
    <hr>
    <div class="panel padding-md panel-default">
      <h4><%= @cardset.title %></h4>
      <div class="panel-body">
        <%= form_for @cardset, url: cardset_path(@cardset) do |f| %>
          <%= render 'form', f: f %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cardsets/index.html.erb
<%= link_to new_cardset_path, :class => "btn btn-fab btn-raised btn-material-red btn-navbar" do %>
  <i class="mdi-content-add text-white"></i>
<% end %>

<div class="row row-animated">
  <div class="col-md-8 col-md-offset-2">
    <h2 class="list-title"><%= t 'title_cardsets' %></h2>
    <hr>
    <% if Category.all.size == 0 %>
    <div class="alert alert-warning">
        <h4><%= t('title_nocategories') %></h4>
        <p><%= t('text_nocategories') %> <strong><%= link_to t('link_nocategories'), new_category_path %></strong></p>
    </div>
    <% end %>
    <% if Cardset.all.size != 0 %>
    <div class="panel">
      <div class="panel-body panel-list">
        <% Cardset.all.each do |cardset| %>
        <div class="row">
          <div class="hidden-xs col-sm-1">
            <i class="mdi-action-question-answer icon-md"></i>
          </div>
          <div class="col-xs-8 col-sm-6">
            <div class="ellipsis">
              <strong><%= link_to strip_tags(cardset.title), cardset_path(cardset), :class => "link-black" %></strong>
            </div>
          </div>
          <div class="hidden-xs col-sm-2">
            <small><%= pluralize(cardset.cards.size, t('card')) %></small>
          </div>
          <div class="col-xs-4 col-sm-3">
            <div class="pull-right">
              <%= link_to edit_cardset_path(cardset), :class => "link-icon" do %>
                <i class="mdi-content-create"></i>
              <% end %>
              <%= link_to cardset_path(cardset), method: :delete,
                          data: { confirm: t('text_confirmdelete') }, :class => "link-icon" do %>
                <i class="mdi-action-delete"></i>
              <% end %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <% else %>
    <div class="alert alert-warning">
      <h4><%= t('title_nocardsets') %></h4>
      <p><%= t('text_nocardsets') %> <strong><%= link_to t('link_nocardsets'), new_cardset_path %></strong></p>
    </div>
    <% end %>
  </div>
</div>

app/views/cardsets/new.html.erb
<div class="row row-animated">
  <div class="col-md-6 col-md-offset-3">
    <h2 class="list-title">
      <%= link_to cardsets_path, :class => "link-icon icon-xl" do %>
        <i class="mdi-navigation-arrow-back"></i>
      <% end %>
    <%= t('title_new_cardset') %>
    </h2>
    <hr>
    <div class="panel padding-md panel-default">
      <div class="panel-body">
        <%= form_for @cardset, url: cardsets_path do |f| %>
          <%= render 'form', f: f %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cardsets/show.html.erb
<%= link_to new_cardset_card_path(@cardset), :class => "btn btn-fab btn-raised btn-material-red btn-navbar" do %>
  <i class="mdi-content-add text-white"></i>
<% end %>

<div class="row row-animated">
  <div class="col-md-8 col-md-offset-2">
      <span class="pull-right">
        <%= link_to cardset_presentation_path(@cardset), :class => "link-icon" do %>
          <i class="mdi-action-view-carousel" data-toggle="tooltip" data-placement="top" title="<%= t('action_presentation') %>"></i>
        <% end %>
      </span>
      <h2 class="list-title">
        <%= link_to cardsets_path, :class => "link-icon icon-xl" do %>
          <i class="mdi-navigation-arrow-back"></i>
        <% end %>
        <%= @cardset.title %> <small><%= pluralize(@cardset.cards.size, t('card')) %></small>
      </h2>
      <hr>
    <% if Category.all.size != 0 %>
      <% if @cardset.cards.size != 0 %>
      <% Category.all.order("id asc").each do |category| %>
        <% if @cardset.cards.where(:category_id => category.id).any? %>
        <h4 class="list-title">
          <%= category.title %> <small><%= pluralize(@cardset.cards.where(:category_id => category.id).size, t('card')) %></small>
        </h4>
        <div class="panel">
          <div class="panel-body panel-list">
            <% ellipsis = false %>
            <% @cardset.cards.where(:category_id => category.id).order("id asc").each_with_index do |card, n| %>
            <% if ((n > 2) && (n != (@cardset.cards.where(:category_id => category.id).size - 1))) %>
              <% if !ellipsis %>
                <% ellipsis = true %>
                <div class="row text-center" data-category="<%= category.id %>" onClick="$(this).slideUp(200, function(){$(this).siblings('.row-collapsed').slideToggle();});" style="cursor: pointer;" data-toggle="tooltip" title="<%= t('text_showmorequestions', number: (@cardset.cards.where(:category_id => category.id).size - 4))%>">
                  <a href="javascript:void(0);" class="link-icon" style="line-height: 100%;"><i class="mdi-navigation-more-vert"></i></a>
                </div>
              <% end %>
            <div class="row row-collapsed" data-category="<%= category.id %>" >
            <% else %>
            <div class="row" data-category="<%= category.id %>" >
            <% end %>
              <div class="hidden-xs col-sm-1">
                <i class="mdi-communication-messenger icon-md"></i>
              </div>
              <div class="col-xs-6 col-sm-8">
                <div class="ellipsis width-sm">
                  <strong><%= link_to strip_tags(card.question), edit_cardset_card_path(:id => card, :cardset_id => @cardset), :class => "link-black" %></strong>
                </div>
              </div>
              <div class="col-xs-4 col-sm-3 actions">
                <div class="pull-right">
                  <%= link_to edit_cardset_card_path(:id => card, :cardset_id => @cardset), :class => "link-icon" do %>
                    <i class="mdi-content-create"></i>
                  <% end %>
                  <%= link_to cardset_card_path(:id => card, :cardset_id => @cardset), method: :delete, :class => "link-icon" do %>
                    <i class="mdi-action-delete"></i>
                  <% end %>
                </div>
              </div>
            </div>
            <% end %>
          </div>
        </div>
        <% end %>
      <% end %>
      <% else %>
      <div class="alert alert-warning">
        <h4><%= t('title_nocards') %></h4>
        <p><%= t('text_nocards') %> <strong><%= link_to t('link_nocards'), new_cardset_card_path(@cardset) %></strong></p>
      </div>
      <% end %>
    <% else %>
    <div class="alert alert-warning">
        <h4><%= t('title_nocategories') %></h4>
        <p><%= t('text_nocategories') %> <strong><%= link_to t('link_nocategories'), new_category_path %></strong></p>
    </div>
    <% end %>
  </div>
</div>
</div>