config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :cardsets do
    resources :cards, except: [:index, :show]

    get :presentation, to: "presentations#show"
  end

  resources :presentations, only: :index
  resources :categories, except: :show

  namespace :api do
    resources :cardsets, only: :show
    resources :categories, only: :index
  end

  root to: redirect("/presentations")
end

# == Route Map
#
#               Prefix Verb   URI Pattern                                    Controller#Action
#     new_user_session GET    /users/sign_in(.:format)                       devise/sessions#new
#         user_session POST   /users/sign_in(.:format)                       devise/sessions#create
# destroy_user_session DELETE /users/sign_out(.:format)                      devise/sessions#destroy
#        cardset_cards POST   /cardsets/:cardset_id/cards(.:format)          cards#create
#     new_cardset_card GET    /cardsets/:cardset_id/cards/new(.:format)      cards#new
#    edit_cardset_card GET    /cardsets/:cardset_id/cards/:id/edit(.:format) cards#edit
#         cardset_card PATCH  /cardsets/:cardset_id/cards/:id(.:format)      cards#update
#                      PUT    /cardsets/:cardset_id/cards/:id(.:format)      cards#update
#                      DELETE /cardsets/:cardset_id/cards/:id(.:format)      cards#destroy
# cardset_presentation GET    /cardsets/:cardset_id/presentation(.:format)   presentations#show
#             cardsets GET    /cardsets(.:format)                            cardsets#index
#                      POST   /cardsets(.:format)                            cardsets#create
#          new_cardset GET    /cardsets/new(.:format)                        cardsets#new
#         edit_cardset GET    /cardsets/:id/edit(.:format)                   cardsets#edit
#              cardset GET    /cardsets/:id(.:format)                        cardsets#show
#                      PATCH  /cardsets/:id(.:format)                        cardsets#update
#                      PUT    /cardsets/:id(.:format)                        cardsets#update
#                      DELETE /cardsets/:id(.:format)                        cardsets#destroy
#        presentations GET    /presentations(.:format)                       presentations#index
#           categories GET    /categories(.:format)                          categories#index
#                      POST   /categories(.:format)                          categories#create
#         new_category GET    /categories/new(.:format)                      categories#new
#        edit_category GET    /categories/:id/edit(.:format)                 categories#edit
#             category PATCH  /categories/:id(.:format)                      categories#update
#                      PUT    /categories/:id(.:format)                      categories#update
#                      DELETE /categories/:id(.:format)                      categories#destroy
#          api_cardset GET    /api/cardsets/:id(.:format)                    api/cardsets#show
#       api_categories GET    /api/categories(.:format)                      api/categories#index
#                 root GET    /                                              redirect(301, /presentations)

app/models/card.rb
# frozen_string_literal: true

class Card < ApplicationRecord
  belongs_to :category
  belongs_to :cardset

  validates :question,
            presence: true

  validates :answer,
            presence: true
end

# == Schema Information
#
# Table name: cards
#
#  id          :bigint           not null, primary key
#  answer      :text
#  question    :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  cardset_id  :integer
#  category_id :integer
#
# Indexes
#
#  index_cards_on_cardset_id   (cardset_id)
#  index_cards_on_category_id  (category_id)
#

app/controllers/cards_controller.rb
# frozen_string_literal: true

class CardsController < ApplicationController
  before_action :authenticate_user!

  def new
    @card = Card.new
    @cardset = cardset
  end

  def create
    @card = Card.new(card_params.merge(cardset: cardset))
    @cardset = cardset

    if @card.save
      redirect_to cardset_path(@cardset)
    else
      render "new"
    end
  end

  def edit
    @card = card
    @cardset = cardset
  end

  def update
    @card = card
    @cardset = cardset

    if @card.update(card_params)
      redirect_to cardset_path(@cardset)
    else
      render "edit"
    end
  end

  def destroy
    @card = card
    @cardset = cardset

    @card.destroy

    redirect_to cardset_path(@cardset)
  end

  private

  def card_params
    params
      .require(:card)
      .permit(:question, :answer, :category_id)
  end

  def card
    @card ||= Card.find(params[:id])
  end

  def cardset
    @cardset ||= Cardset.find(params[:cardset_id])
  end
end

app/views/cards/_form.html.erb
<% if @card.errors.any? %>
<div id="error_explanation" class="alert alert-danger">
  <strong><%= pluralize(@card.errors.count, t('error')) %> <%= t('card_errortext') %></strong>
  <ul>
  <% @card.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <%= f.text_area :question, :class => "form-control floating-label", :placeholder => t('question').capitalize, :required => "true", :rows => "5" %>
</div>

<div class="form-group">
  <%= f.text_area :answer, :class => "form-control floating-label", :placeholder => t('answer').capitalize, :required => "true", :rows => "5" %>
</div>

<div class="form-group margin-top-md">
  <%= f.select(:category_id, {}, {}, { :class => "select form-control floating-label", :placeholder => t('category').capitalize }) do %>
    <%= options_for_select(Category.all.collect {|cat| [ cat.title, cat.id ] }, @card.category_id) %>
  <% end %>
</div>

<% if params[:action] != 'new' %>
<%= f.submit t('action_update'), :class => "btn" %>
<% else %>
<%= f.submit t('action_add'), :class => "btn" %>
<% end %>

app/views/cards/edit.html.erb
<div class="row row-animated">
  <div class="col-lg-6 col-lg-offset-3">
    <h2 class="list-title">
      <%= link_to cardset_path(@cardset), :class => "link-icon icon-xl" do %>
        <i class="mdi-navigation-arrow-back"></i>
      <% end %>
      <%= t('action_edit') %>
    </h2>
    <hr>
    <div class="well well-lg">
      <div class="panel-body">
        <%= form_for @card, url: cardset_card_path(:id => @card, :cardset_id => @cardset) do |f| %>
          <%= render 'form', f: f %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cards/new.html.erb
<div class="row row-animated">
  <div class="col-lg-8 col-lg-offset-2">
    <h2 class="list-title">
      <%= link_to cardset_path(@cardset), :class => "link-icon icon-xl" do %>
        <i class="mdi-navigation-arrow-back"></i>
      <% end %>
      <%= t('title_add_card') %>
    </h2>
    <hr>
    <% if Category.all.size == 0 %>
    <div class="alert alert-warning">
        <h4><%= t('title_nocategories') %></h4>
        <p><%= t('text_nocategories') %> <strong><%= link_to t('link_nocategories'), new_category_path %></strong></p>
    </div>
    <% end %>
    <div class="well well-lg">
      <div class="panel-body">
        <%= form_for @card, url: cardset_cards_path do |f| %>
          <%= render 'form', f: f %>
        <% end %>
      </div>
    </div>
  </div>
</div>